export const ITEMS_LOADING = 'ITEMS_LOADING';
export const GET_ITEMS = 'GET_ITEMS';
export const ITEMS_FAILED = 'ITEMS_FAILED';

export const GIGS_LOADING = 'GIGS_LOADING';
export const GET_GIGS = 'GET_GIGS';
export const GIGS_FAILED = 'GIGSS_FAILED';

export const MUSICIANS_LOADING = 'MUSICIANS_LOADING';
export const GET_MUSICIANS = 'GET_MUSICIANS';
export const MUSICIANS_FAILED = 'MUSICIANS_FAILED';

export const INSTRUCTORS_LOADING = 'INSTRUCTORS_LOADING';
export const GET_INSTRUCTORS = 'GET_IINSTRUCTORS';
export const INSTRUCTORS_FAILED = 'INSTRUCTORS_FAILED';